language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.6
      script:
        - pycodestyle --max-line-length=120 diffprivlib
        - pylint -rn diffprivlib

install:
  - pip install pylint pycodestyle
  - pip install .

script:
  - pytest
