language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: 3.7
      script:
        - (pycodestyle --max-line-length=120 diffprivlib || exit 0) && (pylint -rn diffprivlib || exit 0)
  allow_failures:
    - python: 3.8
      script:
        - pytest

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install scikit-learn==0.20.3;
    fi
  - pip install pylint pycodestyle
  - pip install .

script:
  - pytest
