language: python
dist: trusty
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
  - sudo apt-get install -y pycodestyle

script:
  - pytest
  - pycodestyle --max-line-length=121
