language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.6
      script:
        - pycodestyle --max-line-length=120 diffprivlib
        - pylint -rn diffprivlib || exit 0

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install scikit-learn==0.20.3;
    fi
  - pip install pylint pycodestyle
  - pip install .

script:
  - pytest
